notifications:
  email: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64
           ARCH=x86_64
    #- sudo: required
    #  services:
    #    - docker
    #  env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686
    #       PRE_CMD=linux32
    #       ARCH=i386

install:
  - docker pull $DOCKER_IMAGE

script:
  - docker run -e ARCH=$ARCH --rm -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/build-wheels.sh
  - ls wheelhouse/
